version: '3.8'
services:
  # api:
    # container_name: next-blog
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # ports:
    #   - 3000:3000
    # # env_file:
    # #   - .env
    # depends_on:
    #   - postgres
    # command: bash -c "npm run prisma:migrate:dev"

  postgres:
    container_name: nuxt-blog
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env





volumes:
  postgres_data:
